### ISSUE TITLE
"body max limit reached: http: request body too large" since 1.2.0

### ISSUE THREAD

**Issue by igoooor** [acouvreur/traefik-modsecurity-plugin#9]
Hello,

Since I updated to 1.2.0, a simple post request (not uploading files) gives this error message:
`body max limit reached: http: request body too large`

Reverting to 1.1.0 fixes the problem.

**Comment by igoooor** [comment]
ah, I just found out it is the new configuration

**Comment by igoooor** [comment]
Would it be possible that the default 10Mb is somehow smaller than 10Mb?
Because it was really a simple post request (just submitting a login form) and I got the message above, with the default `maxBodySize`

**Comment by Enrico204** [comment]
It should not, there is a test in the configuration and the max is configured here: https://github.com/acouvreur/traefik-modsecurity-plugin/blob/bf893e0295e9d6b71f768bdfc1271cf28e07ac77/modsecurity.go#L51

You may check the POST size using the Firefox/Chrome development toolbar. If it's bigger than 10MB, then you can tune the `maxBodySize` parameter.

If it's smaller, then we may indeed have a bug :-)

**Comment by igoooor** [comment]
I will test v1.2.0 more during the night (CET)

**Comment by igoooor** [comment]
so could #10 be the cause of my problems here?

**Comment by acouvreur** [comment]
> so could #10 be the cause of my problems here?

I think it is
